version: '3.4'

services:
  familytree.api:
    image: ${DOCKER_REGISTRY-}familytreeapi
    build:
      context: .
      dockerfile: FamilyTree.Api/Dockerfile
  db:
    image: postgres
    restart: always
    ports:
     - 5432:5432
    environment:
        POSTGRES_PASSWORD: example
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 80:80
    environment:
        PGADMIN_DEFAULT_EMAIL: runivormadal@gmail.com
        PGADMIN_DEFAULT_PASSWORD: example